---
- name: Install Grafana on the system
  hosts: control
  tasks:
    - name: Install Grafana on Debian Systems
      when: ansible_os_family == "Debian"
      become: true
      block:

        - name: Downlaod Grafana GPG key for debian
          ansible.builtin.get_url:
            url: https://apt.grafana.com/gpg.key
            dest: /usr/share/keyrings/grafana.key
            mode: '0644'

        - name: Add Grafana apt repository on Debian
          ansible.builtin.copy:
            dest: /etc/apt/sources.list.d/grafana.list
            content: |
              deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main
            mode: '0644'

        - name: Install Grafana
          ansible.builtin.apt:
            pkg:
              - grafana
              - grafana-enterprise
            state: present
            update_cache: true
    
    - name: Install Grafana on RedHat Systems
      when: ansible_os_family == "RedHat"
      become: true
      block:

        - name: Download the GPG key on RedHat based systems
          ansible.builtin.get_url:
            url: https://rpm.grafana.com/gpg.key
            dest: /etc/pki/rpm-gpg/RPM_GPG_KEY_grafana
            mode: '0644'

        - name: Add Grafana repository on RedHat based systems
          ansible.builtin.copy:
            dest: /etc/yum.repos.d/grafana.repo
            content: |
              [grafana]
              name=grafana
              baseurl=https://rpm.grafana.com/rpm/stable/x86_64/
              gpgcheck=1
              gpgkey=file:///etc/pki/rpm-gpg/RPM_GPG_KEY_grafana
            mode: '0644'

        - name: Install Grafana
          ansible.builtin.dnf:
            pkg:
              - grafana
              - grafana-enterprise
            state: present

    - name: cheak if firewalld is running
      ansible.builtin.systemd:
        name: firewalld
      register: firewalld_status

      
    - name: Output firewalld status
      ansible.builtin.debug:
        msg: "Firewalld status: {{ firewalld_status.status.ActiveState }}"


    - name: Open firewalld status
      ansible.posix.firewalld:
        #zone: public
        port: 3000
        permanent: true
        state: enabled
      when: firewalld_status.status.ActiveState == "active"

    - name: Start Grafana service
      ansible.builtin.systemd:
        name: grafana-server
        state: started
        enabled: true
